version: '3'

services: 

  app:
    build: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s yarn start
    networks: 
      - node-network
    tty: true
    depends_on: 
      - db
    environment:
      - HTTP_PORT=3000

  nginx:
    build:
      context: .docker/nginx
    ports:
      - "8080:80"
    networks:
      - node-network

  db:
    build:
      context: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    # volumes: 
    #   - ./mysql/dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      